baseURL = 'https://cconroy.com/'
languageCode = 'en-us'
title = 'cconroy.com'
theme = 'minimal-blog'

[params]
copyrightedBy = 'Charles Conroy'
lead = 'mostly programmings'
alternateTitle = "home"

[pagination]
pagerSize = 5

[markup.highlight]
noClasses = false

[taxonomies]
tag = "tags"

[outputs]
home = ['HTML', 'RSS']
section = ['HTML', 'RSS']
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[outputFormats.RSS]
baseName = 'rss'
